version: 2.1

workflows:
  version: 2.1
  build-test:
    jobs:
      - checkout

      - dependencies:
          requires:
            - checkout

      - build-test:
          requires:
            - dependencies
          context:
            Kwetter

jobs:
  checkout:
    working_directory: ~/kwetter-backend

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - persist_to_workspace:
          root: .
#          path:
#            - kwetter-backend

  dependencies:
    working_directory: ~/kwetter-backend

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - restore_cache:
          key: kwetter-backend-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: kwetter-backend-{{ checksum "pom.xml" }}

  build-test:
    working_directory: ~/kwetter-backend

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
#      - checkout

      #      - restore_cache:
      #          key: kwetter-backend-{{ checksum "pom.xml" }}
      #
      #      - run: mvn dependency:go-offline
      #
      #      - save_cache:
      #          paths:
      #            - ~/.m2
      #          key: kwetter-backend-{{ checksum "pom.xml" }}

      - run:
          name: building
          command: mvn package

      - run:
          name: testing
          command: mvn test

      - run:
          name: sonarqube
          command: |
            mvn sonar:sonar \
              -Dsonar.projectKey=RikvanSpreuwel_JEA6-Kwetter-backend \
              -Dsonar.organization=rikvanspreuwel-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_LOGIN_BACKEND

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples