version: 2
jobs:
  build:
    working_directory: ~/kwetter-backend

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          key: kwetter-backend-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: kwetter-backend-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results: 
          path: target/surefire-reports
      
      - store_artifacts: 
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples 