version: 2.1

workflows:
  version: 2.1
  build-test:
    jobs:
      - checkout

      - dependencies:
          requires:
            - checkout

      - build:
          requires:
            - dependencies
      
      - test:
          requires:
            - build

      - sonarqube:
          requires:
            - build
          context:
            Kwetter

executors:
  java:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

commands:
  persist_kwetter_workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths: .
  
  attach_kwetter_workspace:
    steps:
      - attach_workspace:
          at: .

  restore_cache_dependencies:
    steps:
      - restore_cache:
          key: kwetter-backend-{{ checksum "pom.xml" }}

jobs:
  checkout:
    executor: java
    steps:
      - checkout
      - persist_kwetter_workspace

          #not sure if dependencies are persisted to the next job

  dependencies:
    executor: java
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: kwetter-backend-{{ checksum "pom.xml" }}

  build:
    executor: java
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies
      - run:
          name: building
          command: mvn -B -DskipTests clean package
      - persist_kwetter_workspace

  test:
    executor: java
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies
      - run:
          name: testing
          command: mvn test

      - store_test_results:
          path: target/surefire-reports 
  
  sonarqube:
    executor: java
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies
      - run:
          name: sonarqube
          command: |
            mvn sonar:sonar \
              -Dsonar.projectKey=RikvanSpreuwel_JEA6-Kwetter-backend \
              -Dsonar.organization=rikvanspreuwel-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_LOGIN_BACKEND



  # build-test:
  #   executor: java
  #   steps:
  #     - attach_kwetter_workspace

      # - run:
      #     name: building
      #     command: mvn package

      # - run:
      #     name: testing
      #     command: mvn test

      # - run:
      #     name: sonarqube
      #     command: |
      #       mvn sonar:sonar \
      #         -Dsonar.projectKey=RikvanSpreuwel_JEA6-Kwetter-backend \
      #         -Dsonar.organization=rikvanspreuwel-github \
      #         -Dsonar.host.url=https://sonarcloud.io \
      #         -Dsonar.login=$SONAR_LOGIN_BACKEND

      
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples



            #      - checkout

            #      - restore_cache:
            #          key: kwetter-backend-{{ checksum "pom.xml" }}
            #
            #      - run: mvn dependency:go-offline
            #
            #      - save_cache:
            #          paths:
          #            - ~/.m2
          #          key: kwetter-backend-{{ checksum "pom.xml" }}